#!/usr/bin/env python

import json
import argparse
from metis.Utils import make_tarball


def main(args):

    if not args.cmssw:
        make_tarball(args.output)
    else:
        make_tarball(args.output, override_cmssw_base=args.cmssw)

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("output", help="name of output tar file")
    parser.add_argument("-c", "--cmssw", help="CMSSW_BASE directory, default is $CMSSW_BASE", default=None)

    args = parser.parse_args()

    main(args)
